### ISSUE TITLE
There are issues with the Dutch (NL) version of the tutorial

### ISSUE THREAD

**Issue by Funkyplanet** [gjtorikian/markdowntutorial.com#134]
As i got stuck/confused a bit on the last exercise from part 3 of the tutorial in English, i thought i would check it out in my native language Dutch.  But in part one i aleady stumbled upon an error in the instruction of excercise 2 and although i completed exercise 3 by making the words in the instruction italic and bold it didn't complete the exercise. 

 
![image](https://github.com/gjtorikian/markdowntutorial.com/assets/125372068/cf2cc02f-6617-462b-8a90-2268110c1d37)

![image](https://github.com/gjtorikian/markdowntutorial.com/assets/125372068/f99891c6-fd54-4121-9836-bbfd068ab385)

This tutorial is certainly very helpfull to learn the basics of Markdown for a beginner like me, but i think that there are some tweaks needed in the Dutch version of it.

**Comment by gjtorikian** [comment]
Hey, many thanks for the report! This should be fixed now.
