### ISSUE TITLE
unable to do the exercises

### ISSUE THREAD

**Issue by gordon-chime** [gjtorikian/markdowntutorial.com#142]
The tutorial no longer works.

The exercise windows don't appear.

It's a great tutorial, by the way—concise and to the point, with exercises.

Please fix it.

**Comment by SaintNameless** [comment]
The tutorial no longer works either. Please fix it.

**Comment by gjtorikian** [comment]
fixed now!

**Comment by gordon-chime** [comment]
Thank you so much. 
v.r.
Gordon Chime
 
PS: If you have the time, please consider creating other tutorials.
     On Wednesday, October 23, 2024 at 01:46:04 PM CDT, Garen Torikian ***@***.***> wrote:  
 
 


Closed #142 as completed.
