### ISSUE TITLE
Vietnamese version

### ISSUE THREAD

**Issue by NGH14** [gjtorikian/markdowntutorial.com#143]
Hi, 

Would you mind if I create the Vietnamese version - my mother tongue, in your tutorial. If possible please give me guideline about the file that needed to translate or any rule need to follow, 

Thank you.

**Comment by gjtorikian** [comment]
Hi, that sounds great!

I really should write out a guide for how to create translations. But, basically, you need to change 13 files: https://github.com/gjtorikian/markdowntutorial.com/pull/90/files#diff-7449d985b291b67f665a0d13f402adc1360089a2a000638636e55d28e8465028

The majority of the text is in the `lessons`, folder, everything else deals with country codes and routing (which for you would be `vi-VN`). Let me know if you need more guidance, happy to help!

**Comment by NGH14** [comment]
Thank for the resource I will put it on the _vi-VN_

**Comment by NGH14** [comment]
@gjtorikian Sorry for bother you but I some bug when I try to run `jekyll serve` after I have done translate the `index.md`  and `conclusion.md`  to double check.

```
<internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- erb (LoadError)
Did you mean?  drb
        from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /home/x/.local/share/gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/commands/new.rb:3:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /home/x/.local/share/gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll.rb:13:in `block in require_all'
        from /home/x/.local/share/gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll.rb:12:in `each'
        from /home/x/.local/share/gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll.rb:12:in `require_all'
        from /home/x/.local/share/gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll.rb:188:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from <internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /home/x/.local/share/gem/ruby/3.3.0/gems/jekyll-4.3.4/exe/jekyll:8:in `<top (required)>'
        from /home/x/.local/share/gem/ruby/3.3.0/bin/jekyll:25:in `load'
        from /home/x/.local/share/gem/ruby/3.3.0/bin/jekyll:25:in `<main>' 
 ```

**Comment by gjtorikian** [comment]
I ended up merging #144, because I was able to build the project locally. In your error messages above, I noticed it refers to `3.3.0`—this project uses Ruby 2.7.5, because of a bug in an upstream dependency. Try switching to that version and see if it works.

Thank you again for your translation!
