### ISSUE TITLE
skip button or hint buttons

### ISSUE THREAD

**Issue by gaiapunk** [gjtorikian/markdowntutorial.com#29]
I'm a coding noob training myself on markdown so I can one day be a master October CMS editor.

I love this tutorial!

But, I'm stuck on the last exercise on lesson 6.  I'll likely figure it soon but I was wondering if you would consider including skip on hint buttons for folks like me.

Thanks for the amazing work on this!

**Comment by notafish** [comment]
Loved the tutorial and found it extremely helpful but I have to echo those remarks. Hint or skip button (rather hint ;)) would be great. The problem being that sometimes the "missing" thing is deleting a space that can't be seen in order to trigger the next level. Thanks for this though.

**Comment by nicolasmccurdy** [comment]
I would be interested in implementing a skip button. Maybe it could also show the solution? I like the idea of hints, but I feel like that would be too difficult to implement.

**Comment by gjtorikian** [comment]
Handled by https://github.com/gjtorikian/markdowntutorial.com/pull/40.
