### ISSUE TITLE
Moving to the next task too quickly

### ISSUE THREAD

**Issue by mariocpinto** [gjtorikian/markdowntutorial.com#45]
Hello,

Disclaimer first: I am new to git - so do not know if creating an issue is the 'right' way to provide feedback.

I loved the tutorial and found it very helpful - thanks a bunch!

I had one feedback: when you move from one sub-task to another within the same page, as soon as you put in the correct 'answer' it jumps to the next task without providing any time to observe the output. If some delay is introduced or maybe a next-button at the sub-step level, that might be helpful.

Thanks,
Mario

**Comment by gjtorikian** [comment]
Good suggestion. I'll mark this as something to pick up as time allows.

**Comment by mariocpinto** [comment]
Thanks @gjtorikian !

**Comment by gjtorikian** [comment]
Fixed! See how you like it now.

**Comment by mariocpinto** [comment]
Do I check this on http://markdowntutorial.com/? 

Just to elaborate:
1. I go to the first page of the tutorial.
2. I complete the first task i.e. change not to _not_.
3. This immediately jumps to the next task without sufficient delay to observe the output.

- If you have introduced a delay, it still isn't noticeable to me yet.

**Comment by gjtorikian** [comment]
Oh heh, I forgot to deploy it to the site. You can try now.

**Comment by mariocpinto** [comment]
Yes I see the delay now - Thanks!

Don't want to be picky, but I wonder what the optimum delay time would be (?)
As per one comment [here](http://cogsci.stackexchange.com/questions/1147/how-long-does-it-take-to-read-a-sentence-with-x-number-of-characters ):

> timeToRead=1300+(chars∗65)

So maybe a few seconds (2-3) would be ideal?
