### ISSUE TITLE
Lesson 5: clarify first test by adding quotions around book quote

### ISSUE THREAD

**Issue by andrewholgate** [gjtorikian/markdowntutorial.com#48]
Firstly, thank you for this great resource! We are using markdowntutorial.com as a tool to teach our editors how to use markdown.

We have seen a few editors have issues with the first part of Lesson 5: blockquote. For them, it is not clear that the second sentence is the book quotation. I think it would be easier to identify if one (or both) of the following changes were made:

1. Add quotations around the book quotation.
1. Add an extra line between "I read this interesting quote the other day:" and the book quotation.

For example:

```
I read this interesting quote the other day:

"Her image had passed into his soul for ever and no word had broken the holy silence of his ecstasy. Her eyes had called him and his soul had leaped at the call. To live, to err, to fall, to triumph, to recreate life out of life! A wild angel had appeared to him, the angel of mortal youth and beauty, an envoy from the fair courts of life, to throw open before him in an instant of ecstasy the gates of all the ways of error and glory. On and on and on and on!"
```

**Comment by gjtorikian** [comment]
Done! I also made the first quote much shorter and simpler.
