### ISSUE TITLE
Link points to http://null in Lesson 3 'Links'

### ISSUE THREAD

**Issue by imrek** [gjtorikian/markdowntutorial.com#50]
I have just experimented with linking to different sites using the text box on [this page](http://www.markdowntutorial.com/lesson/3/) and noticed that sometimes the link evaluates to ```http://null```. I guess it happens if you omit 'www' from the URL (e.g. ```http://google.com```, which is actually valid and understood by the browser).

**Comment by gjtorikian** [comment]
Thanks! I've just fixed this.
