### ISSUE TITLE
Problem with 2nd part in lesson 2?

### ISSUE THREAD

**Issue by ZENN0N** [gjtorikian/markdowntutorial.com#59]
Scratch pad started with this

> In the box below, make the first line a heading level four, and italicize the name of the book:
```
Colombian Symbolism in One Hundred Years of Solitude

Here's some words about the book _One Hundred Years..._.
```

Name of the book appears to be already italicized, so adding the heading level, but can't seem to proceed
```
####Colombian Symbolism in One Hundred Years of Solitude

Here's some words about the book _One Hundred Years..._.
```

**Comment by gjtorikian** [comment]
You need to italicize the name of the book in the level four heading.
