### ISSUE TITLE
Image too large in lesson 4

### ISSUE THREAD

**Issue by Unfit-Donkey** [gjtorikian/markdowntutorial.com#64]
In lesson 4 of markdowntutorial.com the images in the examples are too large and overflow out of the output zone. My guess at a solution would be to reduce the resolution of the three images.

Browser: Chrome 74
OS: Windows 10 desktop

**Comment by gjtorikian** [comment]
Thanks for the feedback, this is fixed in 6f875399635aa5da69e851cbde8861483f1d5397.
