### ISSUE TITLE
Translate french

### ISSUE THREAD

**Issue by Plumf** [gjtorikian/markdowntutorial.com#69]
I try to translate markdowtutorial.com in french, but i'm not a developper. Could you take informations about the technical structure for translate tutorial ? 
For moment i jus translate page : [1.html](https://github.com/Plumf/markdowntutorial.com/tree/dev-fr). Maybe they are other folders or pages  to be translated. Just in 1.html, it's not possible to translate all practical module for exemple. 
Thank You for all informations that would allow me to translate and propose a complete translation for markdowntutorial.

**Comment by gjtorikian** [comment]
Yes, no problem. Let me write some documentation on how to do this.

**Comment by gjtorikian** [comment]
No, there are many more, like:

* https://github.com/gjtorikian/markdowntutorial.com/blob/5a8e4c8b66c5e8eb86b1d9a0a9d12ccd06819ad8/_data/tooltips.yml
* https://github.com/gjtorikian/markdowntutorial.com/blob/5a8e4c8b66c5e8eb86b1d9a0a9d12ccd06819ad8/lessons/_es/lesson_plans.js

**Comment by Plumf** [comment]
Thank you, I read and translate in french. And i suggest an PR. Direct in master branch ? Or there're one dev branch ?

**Comment by gjtorikian** [comment]
Direct to master.

**Comment by victorhck** [comment]
markdowntutorial grows!! :)
Great to read this!

**Comment by gjtorikian** [comment]
Closed by https://github.com/gjtorikian/markdowntutorial.com/pulls?q=is%3Apr+is%3Aclosed
