### ISSUE TITLE
Can I make a Korean version?

### ISSUE THREAD

**Issue by Wookshin** [gjtorikian/markdowntutorial.com#73]
I think it's a really good site to learn about Mark Down.
Many Koreans will like it if Korean version is created. 
May I proceed with the translation of the Korean version?

**Comment by gjtorikian** [comment]
Yes!

If it is helpful, here are some of the files which need to change: https://github.com/gjtorikian/markdowntutorial.com/pull/71

**Comment by gjtorikian** [comment]
finished
