### ISSUE TITLE
The images on your images sections don't work

### ISSUE THREAD

**Issue by Williams-Leith** [gjtorikian/markdowntutorial.com#82]
Nor do the instructions!

**Comment by gjtorikian** [comment]
The lesson does appear to be working, I just tried it. What language are you trying for? Any other information you can provide? What text are you entering?

**Comment by callagg1** [comment]
Yes the images don't work, you can load the images to picc.io which is handy little image sharing tool!

**Comment by gjtorikian** [comment]
I can't reproduce this on https://www.markdowntutorial.com/lesson/4/, please let me know if there's a specific language or lesson where these images are missing!
