### ISSUE TITLE
The Chinese translation of the section of the list is wrong

### ISSUE THREAD

**Issue by BioYork** [gjtorikian/markdowntutorial.com#85]
Original text.：
>在下面的框中，将**任务**的特征变成子列表。

Should be revised to read:
>在下面的框中，将**人物**的特征变成子列表。

任务 means task.
人物 means characters.

**Comment by gjtorikian** [comment]
Thank you!

**Comment by Eric5545** [comment]
> Original text.：
> 
> >在下面的框中，将**任务**的特征变成子列表。
> 
> 
> 
> Should be revised to read:
> 
> >在下面的框中，将**人物**的特征变成子列表。
> 
> 
> 
> 任务 means task.
> 
> 人物 means characters.
> 
>
